language: objective-c
rvm:
- 2.2.3
osx_image: xcode7.3
branches:
  only:
  - master
  - develop
script: fastlane test && fastlane beta
before_install:
- gem update --system
- brew install imagemagick
- gem install fastlane --no-ri --no-rdoc --no-document
before_script:
- openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in fastlane/certificates/distribution.p12.enc
  -d -a -out fastlane/certificates/distribution.p12
env:
  global:
  - SCHEME="ProkrutObjc"
  - XCODEPROJ_NAME="ProkrutObjc.xcodeproj"
  - XCWORKSPACE_NAME="ProkrutObjc.xcworkspace"
  - INFO_PLIST_PATH="ProkrutObjc/Info.plist"
  - APP_IDENTIFIER="com.rambler.ProkrutObjc"
  - secure: OYP01uy+oAyC13FqwEKOZxwXeugjUQMH43Gyra6o1et8SJd1692IXS66GbrCmluQJrkAGEYd1YX3Y7jEQ4Et+/P5Tc+MFLG1hEhfdmoZoefM/3uA6bwSRSsX8u1YrI+yOQ0YEKlTiwaCmK6SCoUTbkoOT4BM9CBbbvsvil/pZk5bSo1TTTEqajefL0Yj9/dJxPyYCYIpXVwAQ9AjCTaBX5w5DyLs7pqjsYYrOgZ7houvSSiTq7/2tbOa1wHe2g8HzKhjtI8c5M6YtHHVtQ7BLcex7c0nH+6F7ILvxZ3+g56zhOsqQkV9mDD9M7tudgDpKTa8nlMdZRusv1wHdjTqdGVB7i7BXRULyReFDtaPmVZkcjqNSyisoDNjQKzyB5VjQ/m2wZ0LKbzjH3iZzXq45mAnxIE64dXu547UGSlpOSa/Z06LjiPcV3acQbhj5/qoqEopyiFYZ2sbe+9+yuTHgaYPA5r/l52Z8RKq+RBNnN8PFTx6V/2XDRuwoVQfvHhyGQaWUM5f3v3Z5DEI7ooXoCRrYvi9aBZ4obBpCZcm7NqbfHsJWdUCLYUfAONj0s7a9QdiNJH3o6yI4vn8EiaLozj9lilQKcCwqOWoDdqd0/iZXTB07NVihrv4aMvGPv/DCDCiLAll2UqdhTLXH7BvWpQQvyeljBcAMNDY6W/f8Hk=
  - secure: RowVkGXGMXrS2DyQj9u0h1MTGBroL0p77OPo+ihq4nMjAcKAZzM8mP3kbPWEgAfpEJiA0SkQOOCMsyrLfHoFEa9OYLy7ZCwxSGXQIYvzC5bBGhsXYuGvu7CLZ+OVgpdasqMVDNJK5DAxE1+VNUol3Vc2wFmKh16s1PYRlCe3quRPcLBKGHxr2tN12BvViHdeBb5SXWuNLKqhnqJ/hlQgLyesX0kKfxM9EZRSXRPmXD/RxLLoPlsnzvgAXZhEUoMScg22gIZ9QVPj5l4QqgSff1A28OAsz7GRpwBD4onMA/Fuu1jpmP8b8eKUnVTNQNUqNOsLIk7mfuvg5VjNPOsPuXe+NPVYiGpTK5sJT+aIaZ7MEwQ9u9x3ncp5akQzGyrC66dC16PvvzAkHpHP6/PElmR1oqXNfhE4qUKHyNVueuXBR7opczNiXXqxdDW5hKBnU3pP6nJYJveu6HicmVSg+8onTOIpRX3Gh7LvVYLJmTfiZ1Huq0Qg40vlnOfu1K8Ed3U1ypK5WWOApqH5giZoD0Fthq8r2xBnH9YclS0LHR/RohKaXJrCOYFM2G4hFwrPjdfgweQOnsn308V4ckTfukc15IMqINLkmDbvQlXaWJjASGoX12sqFknohwPko6vk/5wRlyWUjXoyxYRQWgMznQwlTrxQ/2VAwsWjwPUAmQM=
